; PlatformIO Project Configuration File
; ESP32-S3-Touch-LCD-4.3B Picture Frame

[env]
platform = espressif32
board = esp32-s3-devkitc1-n16r8
framework = arduino

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

lib_deps =
    tzapu/WiFiManager@^2.0.17-rc.3
    bblanchon/ArduinoJson@^7.4.2

lib_archive = no

build_src_flags = -I"lib/ESP32_Display_Panel/src" -I"lib/esp-lib-utils/include"

monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder, default

[env:release]
build_type = release
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCONFIG_MBEDTLS_DYNAMIC_BUFFER=1
    -DCONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC=1
    -DLVGL_PORT_AVOID_TEARING_MODE=3
    -DCORE_DEBUG_LEVEL=0
    -O3
    -DLV_CONF_INCLUDE_SIMPLE
    -I src
    -I include
    -I lib
    -I src/models
    -I src/ui
    -I src/net
    -I lib/ESP32_Display_Panel/src
    -I lib/esp-lib-utils/include

[env:debug]
build_type = debug
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCONFIG_MBEDTLS_DYNAMIC_BUFFER=1
    -DCONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC=1
    -DLVGL_PORT_AVOID_TEARING_MODE=3
    -DCORE_DEBUG_LEVEL=4
    -O0
    -g3
    -DLV_CONF_INCLUDE_SIMPLE
    -I src
    -I include
    -I lib
    -I src/models
    -I src/ui
    -I src/net
    -I lib/ESP32_Display_Panel/src
    -I lib/esp-lib-utils/include